name: Snyk

on:
  push:
  workflow_dispatch:

jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      #    - name: Upload the Terraform SARIF file
      #uses: github/codeql-action/upload-sarif@v1
      #with:
      #  sarif_file: main.tf.sarif
    - name: Upload the Docker SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
